# Generated by Django 5.2.14 on 2026-05-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(db_index=True, help_text='Stable release identifier exposed through API metadata.', max_length=40, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('rule_set_version', models.CharField(db_index=True, help_text='Version string for morphology/phonology rules used by this release.', max_length=80)),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='unique_current_data_release')],
            },
        ),
    ]
