# Generated by Django 5.2.14 on 2026-05-12 02:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(help_text='Stable unique key used by provenance and ingestion workflows.', max_length=80, unique=True, validators=[django.core.validators.RegexValidator(message='Source keys must be stable lowercase identifiers prefixed with source_.', regex='^source_[a-z0-9_]+$')])),
                ('title', models.CharField(max_length=255)),
                ('authority_level', models.CharField(max_length=120)),
                ('rights_usage_note', models.TextField()),
                ('ingestion_style', models.TextField()),
                ('current_filename', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('source_key',),
            },
        ),
    ]
