# Generated by Django 5.2.14 on 2026-05-12 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_type', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('request_changes', 'Request changes'), ('deprecate', 'Deprecate'), ('publish', 'Publish')], db_index=True, max_length=32)),
                ('summary', models.CharField(max_length=255)),
                ('rationale', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('decided_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editorial_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-decided_at',),
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('review_note_created', 'Review note created'), ('review_note_resolved', 'Review note resolved'), ('editorial_decision_recorded', 'Editorial decision recorded'), ('record_state_changed', 'Record state changed')], db_index=True, max_length=64)),
                ('target_object_id', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editorial_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editorial_audit_logs', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['target_content_type', 'target_object_id'], name='editorial_a_target__60c32a_idx')],
            },
        ),
        migrations.CreateModel(
            name='EditorialDecisionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_object_id', models.CharField(max_length=80)),
                ('relationship', models.CharField(choices=[('primary', 'Primary'), ('related', 'Related'), ('superseded', 'Superseded'), ('created', 'Created')], default='primary', max_length=32)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_records', to='editorial.editorialdecision')),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_decision_records', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['target_content_type', 'target_object_id'], name='editorial_e_target__a97723_idx')],
                'constraints': [models.UniqueConstraint(fields=('decision', 'target_content_type', 'target_object_id', 'relationship'), name='unique_editorial_decision_record_relationship')],
            },
        ),
        migrations.CreateModel(
            name='ReviewNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_object_id', models.CharField(max_length=80)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('needs_review', 'Needs review'), ('in_review', 'In review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published'), ('deprecated', 'Deprecated')], db_index=True, default='needs_review', max_length=32)),
                ('body', models.TextField()),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editorial_review_notes', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_review_notes', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['target_content_type', 'target_object_id'], name='editorial_r_target__abec43_idx'), models.Index(fields=['state', 'is_resolved'], name='editorial_r_state_db9d24_idx')],
            },
        ),
    ]
