# Generated by Django 5.2.14 on 2026-05-12 18:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lexicon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FigurativeExpression',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, editable=False, help_text='Stable API-facing identifier derived from the UUID primary key.', max_length=80, unique=True)),
                ('provenance', models.JSONField(blank=True, default=dict, help_text='Source and evidence metadata for tracing canonical record origins.')),
                ('revision', models.PositiveIntegerField(default=1, help_text='Monotonic editorial/data revision for this canonical record.')),
                ('deprecated_at', models.DateTimeField(blank=True, null=True)),
                ('deprecation_note', models.TextField(blank=True)),
                ('phonology_inventory_version', models.CharField(blank=True, max_length=80)),
                ('graphemes', models.JSONField(blank=True, default=list)),
                ('grapheme_count', models.PositiveSmallIntegerField(default=0)),
                ('syllables', models.JSONField(blank=True, default=list)),
                ('syllable_count', models.PositiveSmallIntegerField(default=0)),
                ('expression_text', models.CharField(max_length=255)),
                ('normalized_expression', models.CharField(blank=True, db_index=True, help_text='Conservative search/dedupe key for the expression text.', max_length=255)),
                ('subtype', models.CharField(choices=[('tsumo', 'Tsumo'), ('madimikira', 'Madimikira'), ('madunhurirwa', 'Madunhurirwa'), ('nyaudzosingwi', 'Nyaudzosingwi'), ('fananidzo', 'Fananidzo'), ('enzaniso', 'Enzaniso'), ('chibhende', 'Chibhende')], db_index=True, max_length=32)),
                ('subtype_readiness', models.CharField(choices=[('active', 'Active'), ('reserved', 'Reserved for future support')], db_index=True, default='reserved', max_length=32)),
                ('idiomatic_meaning', models.TextField(blank=True)),
                ('english_rendering', models.TextField(blank=True)),
                ('usage_note', models.TextField(blank=True)),
                ('cultural_themes', models.JSONField(blank=True, default=list)),
                ('pedagogy_notes', models.JSONField(blank=True, default=list)),
                ('source_notes', models.JSONField(blank=True, default=list)),
                ('review_state', models.CharField(choices=[('draft', 'Draft'), ('needs_review', 'Needs review'), ('in_review', 'In review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published'), ('deprecated', 'Deprecated')], db_index=True, default='draft', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_lemmas', models.ManyToManyField(blank=True, related_name='figurative_expressions', to='lexicon.lemma')),
            ],
            options={
                'ordering': ('normalized_expression', 'subtype', 'expression_text'),
                'indexes': [models.Index(fields=['subtype', 'review_state'], name='figurative__subtype_1f4ce4_idx'), models.Index(fields=['subtype_readiness', 'subtype'], name='figurative__subtype_3a856b_idx'), models.Index(fields=['normalized_expression', 'subtype'], name='figurative__normali_bc9924_idx')],
            },
        ),
    ]
