# Generated by Django 5.2.14 on 2026-05-12 16:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_location_reference', models.CharField(help_text='Stable source locator such as filename, page, line, or entry key.', max_length=255)),
                ('raw_text', models.TextField()),
                ('parser_output', models.JSONField(default=dict)),
                ('parser_name', models.CharField(db_index=True, max_length=120)),
                ('parser_status', models.CharField(choices=[('parsed', 'Parsed'), ('parsed_with_uncertainty', 'Parsed with uncertainty'), ('failed', 'Failed')], db_index=True, max_length=32)),
                ('confidence', models.FloatField(help_text='Parser confidence from 0.0 to 1.0 before editorial review.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('review_state', models.CharField(choices=[('draft', 'Draft'), ('needs_review', 'Needs review'), ('in_review', 'In review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published'), ('deprecated', 'Deprecated')], db_index=True, default='needs_review', max_length=32)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('canonical_record_object_id', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_record_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_units', to='contenttypes.contenttype')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extraction_units', to='sources.source')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['source', 'review_state'], name='extraction__source__97c541_idx'), models.Index(fields=['parser_status', 'review_state'], name='extraction__parser__f14dbd_idx'), models.Index(fields=['canonical_record_content_type', 'canonical_record_object_id'], name='extraction__canonic_146e4b_idx')],
            },
        ),
    ]
