# Generated by Django 5.2.14 on 2026-05-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionunit',
            name='batch_id',
            field=models.CharField(blank=True, db_index=True, help_text='Identifier for the import batch that created this unit.', max_length=120),
        ),
    ]
