# Generated by Django 5.2.14 on 2026-05-12 16:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, editable=False, help_text='Stable API-facing identifier derived from the UUID primary key.', max_length=80, unique=True)),
                ('provenance', models.JSONField(blank=True, default=dict, help_text='Source and evidence metadata for tracing canonical record origins.')),
                ('revision', models.PositiveIntegerField(default=1, help_text='Monotonic editorial/data revision for this canonical record.')),
                ('deprecated_at', models.DateTimeField(blank=True, null=True)),
                ('deprecation_note', models.TextField(blank=True)),
                ('phonology_inventory_version', models.CharField(blank=True, max_length=80)),
                ('graphemes', models.JSONField(blank=True, default=list)),
                ('grapheme_count', models.PositiveSmallIntegerField(default=0)),
                ('syllables', models.JSONField(blank=True, default=list)),
                ('syllable_count', models.PositiveSmallIntegerField(default=0)),
                ('headword', models.CharField(max_length=160)),
                ('normalized_headword', models.CharField(blank=True, db_index=True, max_length=160)),
                ('headword_kind', models.CharField(choices=[('word', 'Word'), ('noun', 'Noun'), ('verb_stem', 'Verb stem'), ('ideophone', 'Ideophone'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=32)),
                ('part_of_speech_code', models.CharField(blank=True, db_index=True, max_length=32)),
                ('part_of_speech_label', models.CharField(blank=True, max_length=120)),
                ('dialects', models.JSONField(blank=True, default=list)),
                ('comparative_bantu_marker', models.BooleanField(default=False)),
                ('review_state', models.CharField(choices=[('draft', 'Draft'), ('needs_review', 'Needs review'), ('in_review', 'In review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published'), ('deprecated', 'Deprecated')], db_index=True, default='draft', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('normalized_headword', 'headword'),
                'indexes': [models.Index(fields=['normalized_headword', 'part_of_speech_code'], name='lexicon_lem_normali_c1f02d_idx'), models.Index(fields=['review_state', 'headword_kind'], name='lexicon_lem_review__393eb9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Sense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, editable=False, help_text='Stable API-facing identifier derived from the UUID primary key.', max_length=80, unique=True)),
                ('provenance', models.JSONField(blank=True, default=dict, help_text='Source and evidence metadata for tracing canonical record origins.')),
                ('revision', models.PositiveIntegerField(default=1, help_text='Monotonic editorial/data revision for this canonical record.')),
                ('deprecated_at', models.DateTimeField(blank=True, null=True)),
                ('deprecation_note', models.TextField(blank=True)),
                ('number', models.PositiveSmallIntegerField(default=1)),
                ('definition', models.TextField()),
                ('dialects', models.JSONField(blank=True, default=list)),
                ('grammar', models.JSONField(blank=True, default=list)),
                ('examples', models.JSONField(blank=True, default=list)),
                ('cross_references', models.JSONField(blank=True, default=list)),
                ('review_state', models.CharField(choices=[('draft', 'Draft'), ('needs_review', 'Needs review'), ('in_review', 'In review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published'), ('deprecated', 'Deprecated')], db_index=True, default='draft', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senses', to='lexicon.lemma')),
            ],
            options={
                'ordering': ('lemma__normalized_headword', 'number'),
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, editable=False, help_text='Stable API-facing identifier derived from the UUID primary key.', max_length=80, unique=True)),
                ('provenance', models.JSONField(blank=True, default=dict, help_text='Source and evidence metadata for tracing canonical record origins.')),
                ('revision', models.PositiveIntegerField(default=1, help_text='Monotonic editorial/data revision for this canonical record.')),
                ('deprecated_at', models.DateTimeField(blank=True, null=True)),
                ('deprecation_note', models.TextField(blank=True)),
                ('phonology_inventory_version', models.CharField(blank=True, max_length=80)),
                ('graphemes', models.JSONField(blank=True, default=list)),
                ('grapheme_count', models.PositiveSmallIntegerField(default=0)),
                ('syllables', models.JSONField(blank=True, default=list)),
                ('syllable_count', models.PositiveSmallIntegerField(default=0)),
                ('form_text', models.CharField(max_length=160)),
                ('normalized_form', models.CharField(blank=True, db_index=True, max_length=160)),
                ('form_kind', models.CharField(choices=[('headword', 'Headword'), ('plural', 'Plural'), ('derived', 'Derived'), ('inflected', 'Inflected'), ('variant', 'Variant'), ('other', 'Other')], db_index=True, default='other', max_length=32)),
                ('dialects', models.JSONField(blank=True, default=list)),
                ('grammar', models.JSONField(blank=True, default=list)),
                ('review_state', models.CharField(choices=[('draft', 'Draft'), ('needs_review', 'Needs review'), ('in_review', 'In review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published'), ('deprecated', 'Deprecated')], db_index=True, default='draft', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='lexicon.lemma')),
                ('sense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms', to='lexicon.sense')),
            ],
            options={
                'ordering': ('lemma__normalized_headword', 'form_kind', 'normalized_form'),
            },
        ),
        migrations.CreateModel(
            name='ToneRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, editable=False, help_text='Stable API-facing identifier derived from the UUID primary key.', max_length=80, unique=True)),
                ('provenance', models.JSONField(blank=True, default=dict, help_text='Source and evidence metadata for tracing canonical record origins.')),
                ('revision', models.PositiveIntegerField(default=1, help_text='Monotonic editorial/data revision for this canonical record.')),
                ('deprecated_at', models.DateTimeField(blank=True, null=True)),
                ('deprecation_note', models.TextField(blank=True)),
                ('pattern', models.CharField(max_length=80)),
                ('notation_system', models.CharField(choices=[('hannan_bracket', 'Hannan bracket'), ('editorial', 'Editorial')], db_index=True, default='hannan_bracket', max_length=32)),
                ('note', models.TextField(blank=True)),
                ('review_state', models.CharField(choices=[('draft', 'Draft'), ('needs_review', 'Needs review'), ('in_review', 'In review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published'), ('deprecated', 'Deprecated')], db_index=True, default='draft', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tone_records', to='lexicon.form')),
                ('lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tone_records', to='lexicon.lemma')),
            ],
            options={
                'ordering': ('lemma__normalized_headword', 'notation_system', 'pattern'),
            },
        ),
        migrations.AddConstraint(
            model_name='sense',
            constraint=models.UniqueConstraint(fields=('lemma', 'number'), name='unique_sense_number_per_lemma'),
        ),
        migrations.AddIndex(
            model_name='form',
            index=models.Index(fields=['normalized_form', 'form_kind'], name='lexicon_for_normali_09189d_idx'),
        ),
        migrations.AddIndex(
            model_name='form',
            index=models.Index(fields=['review_state', 'form_kind'], name='lexicon_for_review__491dde_idx'),
        ),
        migrations.AddIndex(
            model_name='tonerecord',
            index=models.Index(fields=['notation_system', 'pattern'], name='lexicon_ton_notatio_cdcc8a_idx'),
        ),
    ]
