# Generated by Django 5.2.14 on 2026-05-12 20:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NounClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, editable=False, help_text='Stable API-facing identifier derived from the UUID primary key.', max_length=80, unique=True)),
                ('provenance', models.JSONField(blank=True, default=dict, help_text='Source and evidence metadata for tracing canonical record origins.')),
                ('revision', models.PositiveIntegerField(default=1, help_text='Monotonic editorial/data revision for this canonical record.')),
                ('deprecated_at', models.DateTimeField(blank=True, null=True)),
                ('deprecation_note', models.TextField(blank=True)),
                ('class_number', models.CharField(db_index=True, help_text='Readable Shona noun-class identifier such as 1, 1a, 2, or 15.', max_length=16, unique=True)),
                ('display_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('nominal_prefix', models.CharField(blank=True, max_length=32)),
                ('prefix_allomorphs', models.JSONField(blank=True, default=list)),
                ('subject_concord', models.CharField(blank=True, max_length=32)),
                ('object_concord', models.CharField(blank=True, max_length=32)),
                ('possessive_concord', models.CharField(blank=True, max_length=32)),
                ('adjectival_concord', models.CharField(blank=True, max_length=32)),
                ('relative_concord', models.CharField(blank=True, max_length=32)),
                ('associative_concord', models.CharField(blank=True, max_length=32)),
                ('demonstrative_proximal', models.CharField(blank=True, max_length=32)),
                ('demonstrative_medial', models.CharField(blank=True, max_length=32)),
                ('demonstrative_distal', models.CharField(blank=True, max_length=32)),
                ('additional_concords', models.JSONField(blank=True, default=dict, help_text='Reserved slot for later morphology concord types.')),
                ('dialect_overrides', models.JSONField(blank=True, default=dict, help_text="Dialect-keyed morphology overrides, for example {'Z': {'subject_concord': 'u'}}.")),
                ('notes', models.TextField(blank=True)),
                ('review_state', models.CharField(choices=[('draft', 'Draft'), ('needs_review', 'Needs review'), ('in_review', 'In review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published'), ('deprecated', 'Deprecated')], db_index=True, default='draft', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_plural_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='singular_classes', to='lexicon.nounclass')),
            ],
            options={
                'ordering': ('display_order', 'class_number'),
            },
        ),
        migrations.AddField(
            model_name='lemma',
            name='noun_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lemmas', to='lexicon.nounclass'),
        ),
        migrations.AddIndex(
            model_name='nounclass',
            index=models.Index(fields=['review_state', 'class_number'], name='lexicon_nou_review__98c8cb_idx'),
        ),
    ]
