# Generated by Django 5.2.14 on 2026-05-12 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0002_nounclass_lemma_noun_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemma',
            name='communication_contexts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lemma',
            name='curriculum_domains',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lemma',
            name='curriculum_stage',
            field=models.CharField(choices=[('forms_1_2', 'Forms 1-2'), ('forms_3_4', 'Forms 3-4'), ('general_secondary', 'General secondary'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='lemma',
            name='first_appearance_lesson',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='lemma',
            name='first_appearance_locator',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lemma',
            name='first_appearance_page',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='lemma',
            name='first_appearance_source_key',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='lemma',
            name='first_appearance_unit',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='lemma',
            name='frequency_score',
            field=models.FloatField(default=0.0, help_text='Transparent learner-priority score from 0.0 to 1.0.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='lemma',
            name='frequency_tier',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='lemma',
            name='learner_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='lemma',
            name='learner_source_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lemma',
            name='learning_functions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lemma',
            name='register_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='lemma',
            index=models.Index(fields=['learner_level', 'frequency_tier'], name='lexicon_lem_learner_3c2869_idx'),
        ),
        migrations.AddIndex(
            model_name='lemma',
            index=models.Index(fields=['first_appearance_source_key', 'first_appearance_lesson'], name='lexicon_lem_first_a_e2da59_idx'),
        ),
    ]
