# Generated by Django 5.2.14 on 2026-05-25 14:02

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0004_tonerecord_dialects'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='form',
            index=django.contrib.postgres.indexes.GinIndex(fields=['normalized_form'], name='form_text_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='lemma',
            index=django.contrib.postgres.indexes.GinIndex(fields=['normalized_headword'], name='lemma_headword_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
