# Generated by Django 5.2.14 on 2026-09-16 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lexicon", "0007_normalize_casefold"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="form",
            options={
                "ordering": (
                    "lemma__normalized_headword",
                    "form_kind",
                    "normalized_form",
                    "public_id",
                )
            },
        ),
        migrations.AlterModelOptions(
            name="lemma",
            options={"ordering": ("normalized_headword", "headword", "public_id")},
        ),
    ]
