# Generated by Django 5.2.14 on 2026-09-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lexicon", "0008_alter_form_options_alter_lemma_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="plural_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("standard", "Standard"),
                    ("honorific", "Honorific"),
                    ("numerical", "Numerical"),
                ],
                db_index=True,
                default="",
                help_text="For form_kind=plural: which plural this is. Blank when the source records only one, or for non-plural forms.",
                max_length=16,
            ),
        ),
    ]
