# Generated by Django 5.2.14 on 2026-05-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('prefix', models.CharField(db_index=True, help_text='Non-secret key prefix used for lookup and support.', max_length=24, unique=True)),
                ('key_hash', models.CharField(max_length=255)),
                ('plan', models.CharField(choices=[('developer', 'Developer'), ('standard', 'Standard'), ('partner', 'Partner')], db_index=True, default='developer', max_length=32)),
                ('rate_limit_per_minute', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['plan', 'is_active'], name='api_auth_ap_plan_e0d2f4_idx')],
            },
        ),
    ]
